JS Basics, Primitive Data Types
js-tasks-ru/js-20220905_wrolanda pull request #2
Opened 2022-09-12 01:03 UTC by wrolanda

implementation functions 
sortStrings - sorts an array of strings
pick - returns an object with only the listed fields
omit -returns an object with only fields not listed

2022-09-12 01:04 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-12 16:38 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const arrCopy = Object.assign([], arr);
более короткий способ скопировать массив: `const copy = [...arr]`

2022-09-12 16:39 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    arrCopy.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-09-12 16:39 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const argList = Object.entries(fields);
избавьтесь от этой операции `Object.entries(fields)` она здесь не нужна!

2022-09-12 16:40 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    delete resObj[elem[1]];
использовать `delete` в связке с объектом не рекомендуется, ведь копирование объекта `{...obj}` делает `shallow copy` или другими словами неглубокую копию, поэтому удаление может привести к весьма неожиданным последствиям

2022-09-12 16:40 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-12 23:02 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-14 21:32 UTC, dosandk approved these changes
👍 good

2022-09-14 21:33 UTC, merged